apiVersion: v1
kind: ServiceAccount
metadata:
  name: catsrc-deppy-adapter
  namespace: olm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: catsrc-deppy-adapter
rules:
  - apiGroups: ["operators.coreos.com"]
    resources: ["catalogsources"]
    verbs: ["list", "get", "watch"]
  - nonResourceURLs: ["*"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: catsrc-deppy-adapter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: catsrc-deppy-adapter
subjects:
  - kind: ServiceAccount
    name: catsrc-deppy-adapter
    namespace: olm